--- # Kafka Deployment 정의
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: mosaic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        disktype: worker
      containers:
        - name: kafka
          image: ${DOCKERHUB_USERNAME}/mosaic-kafka:${IMAGE_TAG}
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181 # Zookeeper 연결 설정
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-0.kafka.mosaic.svc.cluster.local:9092
          ports:
            - containerPort: 9092 # Kafka 기본 포트

--- # Kafka Service 정의
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: mosaic
spec:
  clusterIP: None # Headless
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
