services:
  member-service:
    container_name: member-service
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-member-service:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    ports:
      - "18081:8080"

  account-service:
    container_name: account-service
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-account-service:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    
    ports:
      - "18082:8080"

  contract-service:
    container_name: contract-service
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-contract-service:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    
    ports:
      - "18083:8080"
  credit-service:
    container_name: credit-service
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-credit-service:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    
    ports:
      - "18084:8080"
  mydata-service:
    container_name: mydata-service
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-mydata-service:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    
    ports:
      - "18085:8080"

  springcloud-gateway:
    container_name: springcloud-gateway
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-springcloud-gateway:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"

  frontend-nginx:
    container_name: nginx
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-frontend-nginx:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일
      - /etc/letsencrypt/live/j12a608.p.ssafy.io/fullchain.pem:/etc/letsencrypt/live/j12a608.p.ssafy.io/fullchain.pem  # 인증서
      - /etc/letsencrypt/live/j12a608.p.ssafy.io/privkey.pem:/etc/letsencrypt/live/j12a608.p.ssafy.io/privkey.pem  # 개인 키
    
  redis:
    container_name: redis
    env_file:
      - .env
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-redis:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "6379:6379"

  zookeeper:
    container_name: zookeeper
    env_file:
      - .env
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-zookeeper:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-kafka:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "9092:9092"      # 내부용 (다른 컨테이너용)
      - "29092:29092"    # 외부용 (GUI용)
    env_file:
      - .env
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://host.docker.internal:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    
  member-db:
    container_name: member-db
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-member-db:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: ${MEMBER_DATASOURCE_URL}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MEMBER_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${MEMBER_DATASOURCE_PASSWORD}
      #ENV MYSQL_DATABASE=mosaic_account
    ports:
      - "3307:3306"
    volumes:
      - member-db-data:/var/lib/mysql

  account-db:
    container_name: account-db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${ACCOUNT_DATASOURCE_URL}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${ACCOUNT_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${ACCOUNT_DATASOURCE_PASSWORD}
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-account-db:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - account-db-data:/var/lib/mysql

  contract-db:
    container_name: contract-db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${CONTRACT_DATASOURCE_URL}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${CONTRACT_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${CONTRACT_DATASOURCE_PASSWORD}
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-contract-db:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - contract-db-data:/var/lib/mysql

  mydata-db:
    container_name: mydata-db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${MYDATA_DATASOURCE_URL}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYDATA_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${MYDATA_DATASOURCE_PASSWORD}
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-mydata-db:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "3310:3306"
    volumes:
      - ./sql-script/mydata:/opt/init-sql
      - mydata-db-data:/var/lib/mysql
  credit-db:
    container_name: credit-db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${CREDIT_DATASOURCE_URL}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${CREDIT_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${CREDIT_DATASOURCE_PASSWORD}
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-credit-db:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "3311:3306"
    volumes:
      - credit-db-data:/var/lib/mysql
  model-credit:
    container_name: model-credit
    env_file:
      - .env
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-model-credit:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "9000:8000"
  model-news:
    container_name: model-news
    env_file:
      - .env
    image: ${DOCKERHUB_USERNAME:-recreatekang}/mosaic-model-news:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "9001:8000"
#
volumes:
    member-db-data:
      driver: local
    account-db-data:
      driver: local
    contract-db-data:
      driver: local
    mydata-db-data:
      driver: local
    credit-db-data:
      driver: local