build_mydata_service:
  variables:
    SERVICE_NAME: mydata-service
    BUILD_CONTEXT: ./back/mydata-service
    K8S_PATH: ./infra/k8s/apis/api-mydata.yml
  extends: .backend-default-build
  rules:
    - changes: modeling/mydata-service/**/*
      when: always
    - when: never

push_mydata_service:
  variables:
    SERVICE_NAME: mydata-service
    BUILD_CONTEXT: ./back/mydata-service
    K8S_PATH: ./infra/k8s/apis/api-mydata.yml
  extends: .backend-default-push
  needs: [build_mydata_service]
  rules: [{ changes: [modeling/mydata-service/**/*] }]
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"'     # 수동 실행도 허용하려면
      when: manual
    - when: never

deploy_mydata_service:
  variables:
    SERVICE_NAME: mydata-service
    BUILD_CONTEXT: ./back/mydata-service
    K8S_PATH: ./infra/k8s/apis/api-mydata.yml
  extends: .backend-default-deploy
  needs: [push_mydata_service]
  rules: [{ changes: [modeling/mydata-service/**/*] }]
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"'     # 수동 실행도 허용하려면
      when: manual
    - when: never
