build_mydata_service:
  variables:
    SERVICE_NAME: mydata-service
    BUILD_CONTEXT: ./back/mydata-service
    K8S_PATH: ./infra/k8s/apis/api-mydata.yml
  extends: .backend-default-build
  rules:
    - changes:
        - back/mydata-service/**/*

push_mydata_service:
  variables:
    SERVICE_NAME: mydata-service
    BUILD_CONTEXT: ./back/mydata-service
    K8S_PATH: ./infra/k8s/apis/api-mydata.yml
  extends: .backend-default-push
  needs: [build_mydata_service]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - back/mydata-service/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - back/mydata-service/**/*
      when: manual
    - when: never

deploy_mydata_service:
  variables:
    SERVICE_NAME: mydata-service
    BUILD_CONTEXT: ./back/mydata-service
    K8S_PATH: ./infra/k8s/apis/api-mydata.yml
  extends: .backend-default-deploy
  needs: [push_mydata_service]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - back/mydata-service/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - back/mydata-service/**/*
      when: manual
    - when: never
