build_account-db:
  variables:
    SERVICE_NAME: account-db
    BUILD_CONTEXT: ./infra/rdbms/account
    K8S_PATH: infra/k8s/databases/db-account.yml
  extends: .backend-default-build
  rules:
    - changes:
        - infra/rdbms/account/**/*

push_account-db:
  variables:
    SERVICE_NAME: account-db
    BUILD_CONTEXT: ./infra/rdbms/account
    K8S_PATH: infra/k8s/databases/db-account.yml
  extends: .backend-default-push
  needs: [build_account-db]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - infra/rdbms/account/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - infra/rdbms/account/**/*
      when: manual
    - when: never

deploy_account-db:
  variables:
    SERVICE_NAME: account-db
    BUILD_CONTEXT: ./infra/rdbms/account
    K8S_PATH: infra/k8s/databases/db-account.yml
  extends: .backend-default-deploy
  needs: [push_account-db]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - infra/rdbms/account/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - infra/rdbms/account/**/*
      when: manual
    - when: never
#test_include_trigger:
# tags:
#  - $GITLAB_USER_EMAIL
#script:
#  - echo "CI 정상 작동 여부 확인"
