build_mydata-db:
  variables:
    SERVICE_NAME: mydata-db
    BUILD_CONTEXT: ./infra/rdbms/mydata
    K8S_PATH: ./infra/k8s/databases/db-mydata.yml
  extends: .backend-default-build
  rules:
    - changes:
        - infra/rdbms/mydata/**/*

push_mydata-db:
  variables:
    SERVICE_NAME: mydata-db
    BUILD_CONTEXT: ./infra/rdbms/mydata
    K8S_PATH: ./infra/k8s/databases/db-mydata.yml
  extends: .backend-default-push
  needs: [build_mydata-db]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - infra/rdbms/mydata/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - infra/rdbms/mydata/**/*
      when: manual
    - when: never

deploy_mydata-db:
  variables:
    SERVICE_NAME: mydata-db
    BUILD_CONTEXT: ./infra/rdbms/mydata
    K8S_PATH: ./infra/k8s/databases/db-mydata.yml
  extends: .backend-default-deploy
  needs: [push_mydata-db]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - infra/rdbms/mydata/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - infra/rdbms/mydata/**/*
      when: manual
    - when: never
#test_include_trigger:
# tags:
#  - $GITLAB_USER_EMAIL
#script:
#  - echo "CI 정상 작동 여부 확인"
