build_member_service:
  variables:
    SERVICE_NAME: member-service
    BUILD_CONTEXT: ./back/member-service
    K8S_PATH: ./infra/k8s/apis/api-member.yml
  extends: .backend-default-build
  rules:
    - changes:
        - back/member-service/**/*
      when: always
    - when: never

push_member_service:
  variables:
    SERVICE_NAME: member-service
    BUILD_CONTEXT: ./back/member-service
    K8S_PATH: ./infra/k8s/apis/api-member.yml
  extends: .backend-default-push
  needs: [build_member_service]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - back/member-service/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - back/member-service/**/*
      when: manual
    - when: never

deploy_member_service:
  variables:
    SERVICE_NAME: member-service
    BUILD_CONTEXT: ./back/member-service
    K8S_PATH: ./infra/k8s/apis/api-member.yml
  extends: .backend-default-deploy
  needs: [push_member_service]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - back/member-service/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - back/member-service/**/*
      when: manual
    - when: never
