build_zookeeper:
  variables:
    SERVICE_NAME: zookeeper
    BUILD_CONTEXT: ./infra/zookeeper
    K8S_PATH: ./infra/k8s/infras/zookeeper.yml
  extends: .backend-default-build
  rules:
    - changes:
        - infra/zookeeper/**/*
      when: always
    - when: never

push_zookeeper:
  variables:
    SERVICE_NAME: zookeeper
    BUILD_CONTEXT: ./infra/zookeeper
    K8S_PATH: ./infra/k8s/infras/zookeeper.yml
  extends: .backend-default-push
  needs: [build_zookeeper]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - infra/zookeeper/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - infra/zookeeper/**/*
      when: manual
    - when: never

deploy_zookeeper:
  variables:
    SERVICE_NAME: zookeeper
    BUILD_CONTEXT: ./infra/zookeeper
    K8S_PATH: ./infra/k8s/infras/zookeeper.yml
  extends: .backend-default-deploy
  needs: [push_zookeeper]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - infra/zookeeper/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - infra/zookeeper/**/*
      when: manual
    - when: never
#test_include_trigger:
# tags:
#  - $GITLAB_USER_EMAIL
#script:
#  - echo "CI 정상 작동 여부 확인"
