server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: default

  application:
    name: contract-service

  datasource:
    url: jdbc:mysql://host.docker.internal:3309/mosaic_contract
    username: contract
    password: 608

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

---