server:
  port: 8080

spring:
  #  config:
  #    activate:
  #      on-profile: docker

  application:
    name: contract-service

  datasource:
    url: ${CONTRACT_DATASOURCE_URL}
    username: ${CONTRACT_DATASOURCE_USERNAME}
    password: ${CONTRACT_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      properties:
        spring.json.trusted.packages: "com.mosaic.payload"