spring:
  application:
    name: springcloud-gateway
  profiles:
    active: docker

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter: DEBUG
    org.springframework.web: DEBUG
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-GATEWAY, docker
      routes:
        - id: test-public-api
          uri: http://member-api:8080
          predicates:
            - Path=/api/member/test/public/**
          filters:
            - StripPrefix=2

        - id: test-api
          uri: http://member-api:8080
          predicates:
            - Path=/api/member/test/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication


        - id: member-api-auth
          uri: http://member-api:8080
          predicates:
            - Path=/api/member/auth/**
          filters:
            - PreserveHostHeader
            - StripPrefix=2

        - id: member-api-need-auth
          uri: http://member-api:8080
          predicates:
            - Path=/api/member/**
          filters:
            - PreserveHostHeader
            - StripPrefix=2
            - name: JwtAuthentication

        - id: account-api
          uri: http://account-api:8080
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication

        - id: contract-api
          uri: http://contract-api:8080
          predicates:
            - Path=/api/contract/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication

        - id: mydata-api
          uri: http://mydata-api:8080
          predicates:
            - Path=/api/mydata/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication

        - id: credit-api
          uri: http://credit-api:8080
          predicates:
            - Path=/api/credit/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: k8s

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-GATEWAY, k8s
        - name: JwtAuthentication
      routes:
        - id: member-service-need-auth
          uri: http://member-service.mosaic.svc.cluster.local:8080
          predicates:
            - Path=/api/member/auth/**
          filters:
            - PreserveHostHeader
            - StripPrefix=2

        - id: member-service
          uri: http://member-service.mosaic.svc.cluster.local:8080
          predicates:
            - Path=/api/member/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication

        - id: account-service
          uri: http://account-service.mosaic.svc.cluster.local:8080
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication

        - id: contract-service
          uri: http://contract-service.mosaic.svc.cluster.local:8080
          predicates:
            - Path=/api/contract/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication

        - id: mydata-service
          uri: http://mydata-service.mosaic.svc.cluster.local:8080
          predicates:
            - Path=/api/mydata/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication

        - id: credit-service
          uri: http://credit-service.mosaic.svc.cluster.local:8080
          predicates:
            - Path=/api/credit/**
          filters:
            - StripPrefix=2
            - name: JwtAuthentication

server:
  port: 8080
