import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import React from 'react';
import './globals.css';

const notoSansKR = Noto_Sans_KR({
  variable: '--font-noto-sans-kr',
  weight: ['300', '400', '500', '700'], // 원하는 굵기 선택
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="ko">
    <body className={`${notoSansKR.variable} antialiased`}>
      {children}
    </body>
  </html>
);

export default RootLayout;
